Rewriting the charm with Juju best practices

diff --git a/hooks/config-changed b/hooks/config-changed
--- a/hooks/config-changed
+++ b/hooks/config-changed
@@ -1,9 +1,53 @@
 #!/bin/bash
-set -e # If any command fails, stop execution of the hook with that error
-adminKey=`config-get adminKey`
+set -ex # If any command fails, stop execution of the hook with that error
+. ~/.ZendServerStatus
+phpVersion="5.5"
+adminKey="adminKey"
 adminKeyHash=`config-get adminKeyHash`
-#/usr/local/zend/bin/zs-manage  restart-php -N $adminKey -K $adminKeyHash
-#php bin/zs-client.php installApp --zpk="<location-of-the-zpk-file>" --target="<the-name-of-the-target>" --baseUri="<baseUri>"
-#open-port 80
-#open-port 10082
-#open-port 10081
+guiPassword=`config-get guiPassword`
+zrayEnable=`config-get zrayEnable`
+production="true"
+private_address=`ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'`
+if  [ "$ZS_installed" = "false" ]; then
+	./install_zs.sh $phpVersion --automatic
+	juju-log "Zend Server installed. Will now proceed to bootstrap if api key hash is available"
+	echo "ZS_installed=true" >> ~/.ZendServerStatus
+fi
+if [ -z "$adminKeyHash" ]; then
+   juju-log "Waiting for admin key hash to bootstrap Zend Server"
+   exit 0
+fi
+if    [ -z "$ZS_api_key_hash" ]; then
+	/usr/local/zend/bin/zs-manage api-keys-add-key -n $adminKey -s $adminKeyHash
+        echo "ZS_api_key_hash"=$adminKeyHash >> ~/.ZendServerStatus
+	echo "ZS_api_key"=$adminKey >> ~/.ZendServerStatus
+fi
+if    [ -z "$ZS_bootstrapped" ] && [ ! -z $guiPassword  ]; then
+	/usr/local/zend/bin/zs-client.sh bootstrapSingleServer --adminPassword=$guiPassword --production=true --acceptEula --wait
+	#/usr/local/zend/bin/zs-manage bootstrap-single-server --adminPassword $guiPassword --acceptEula true
+	echo "ZS_bootstrapped=true" >> ~/.ZendServerStatus
+	echo "ZS_guiPassword=$guiPassword" >> ~/.ZendServerStatus	
+	echo "ZS_zrayEnabled=False" >> ~/.ZendServerStatus
+	open-port 80
+	open-port 443
+	open-port 10082
+	open-port 10081
+	restart=true
+fi
+if    [  "$ZS_bootstrapped" = "true" ] && [ "$guiPassword" != $ZS_guiPassword ]; then
+	/usr/local/zend/bin/zs-client.sh userSetPassword --username admin --password="$ZS_guiPassword" --newPassword="$guiPassword" --confirmNewPassword="$guiPassword" --zskey="$adminKey" --zssecret="$adminKeyHash"
+	echo "ZS_guiPassword=$guiPassword" >> ~/.ZendServerStatus
+fi
+if    [  "$ZS_bootstrapped" = "true" ] && [ "$ZS_zrayEnabled" != $zrayEnable ]; then
+	if [  "${zrayEnable,,}" = "true" ]; then
+		enabled="1"
+	else
+		enabled="0"
+	fi
+	/usr/local/zend/bin/zs-manage store-directive -d 'zray.enable' -v $enabled -N "$adminKey" -K "$adminKeyHash"
+	echo "ZS_zrayEnabled=$zrayEnable" >> ~/.ZendServerStatus
+	restart=true
+fi
+if [ "$restart" = "true" ]; then
+	/usr/local/zend/bin/zs-manage restart-php -N $adminKey -K $adminKeyHash
+fi
diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -1,41 +1,5 @@
 #!/bin/bash
-set -e # If any command fails, stop execution of the hook with that error
-phpVersion=`config-get phpVersion`
-adminKey=`config-get adminKey`
-adminKeyHash=`config-get adminKeyHash`
-guiPassword=`config-get guiPassword`
-orderNumber=`config-get orderNumber`
-licenseKey=`config-get licenseKey`
-production=`config-get production`
-if [ -z "$adminKeyHash" ]; then
-        adminKeyHash=`date +%s | sha256sum | base64 | head -c 64`
-        juju-log  --log-level WARNING "Missing web api key in config.yaml. Generated $adminKeyHash as the key. This is fine in single server scenario but will not work in clustered scenario"
-	relation-set -r $JUJU_RELATION_ID adminKeyHash=$adminKeyHash adminKey=$adminKey
-fi
-juju-log "using Zend server webapi key name '$adminKey' and webapi key hash $adminKeyHash"
-tar xzf files/repo_installer_early_access.tar.gz
-./install_zs.sh $phpVersion --automatic
-/usr/local/zend/bin/zs-manage api-keys-add-key -n $adminKey -s $adminKeyHash
-bootstrap="/usr/local/zend/bin/zs-manage bootstrap-single-server -p $guiPassword -a TRUE   -r $production "
-if [ -n "$licenseKey" ]; then
-	bootstrap="$bootstrap -o  $orderNumber -l $licenseKey"
-fi
-juju-log "Will bootstrap Zend server with $bootstrap and retry"
-set +e
-n=0
-until [ $n -ge 7 ]
-do
-	eval $bootstrap
-        [ $? -eq 0 ] && break
-        n=$[$n+1]
-        sleep 3
-done
-set -e
-#/usr/local/zend/bin/zs-manage  restart-php -N $adminKey -K $adminKeyHash
-open-port 80
-open-port 443
-open-port 10082
-open-port 10081
-#open-port 10060
-#open-port 10063
-#open-port 10070/udp
+set -ex # If any command fails, stop execution of the hook with that error
+echo "ZS_installed=false" >> ~/.ZendServerStatus
+#tar xzf files/repo_installer_early_access.tar.gz
+tar xzf files/repo_installer_beta.tar.gz
